config/routes.rb
Rails.application.routes.draw do
  get 'payments/success'
  get 'payments/failure'

  get 'orders/index'
  get 'orders/show/:id', to: "orders#show", as: "orders_show"

  resources :inboxes, except: [:edit, :update]
  post 'inboxes/message_create/:id', to: 'inboxes#message_create', as: "inbox_message_create"

  resources :addresses, except: [:create, :new, :index]
  resources :items
  get 'item/search(/:query)', to: "items#search", as: "item_search"


  devise_for :users, controllers: {
    registrations: "user/registrations"
  }

  root 'pages#index'
  get 'pages/index'

  get 'sample/sign/in', to: 'pages#sample_sign_in'

  mount ActionCable.server => '/cable'
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :item

    validates :status, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :user_check

  def index
    @orders = current_user.orders.all.includes(:item, :user, item: [:user, images_attachments: :blob], ).sort_by { |o| -o.created_at.to_i }
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
  end

  def create
  end

  protected
  def user_check
    unless user_signed_in?
      redirect_to new_user_session_path, notice: "You cannot access this page without being signed in!"
    end
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="container-fluid">
    <h1 style="text-align:center">Orders</h1>

    <div class="row row-cols-1 row-cols-md-2 g-3 justify-content-center">
        <% @orders.each do |order| %>
            <div class="card mb-3 m-2" style="max-width: 540px; min-width:200px ">
                <div class="row">
                    <% unless order.item.nil? %>
                        <% unless order.item.images[0].nil? %>
                            <div class="col-md-6">
                            <% order.item.images.each do |photo| %>
                                <%= image_tag(photo, :width => 200) %>
                            <% end %>
                            </div>  
                            <div class="col-md-6"> 
                        <% else %>

                            <div class="col-md-"> 

                        <% end%>
                            <div class="card-body">
                                <strong><%= order.item.description %></strong>
                                <br>
                                <br>
                                <strong>Seller: </strong>
                                <%= order.item.user.email %>
                                <br>
                                <strong>Date of Purchase: </strong><%= order.created_at %>
                                <br>
                                <%= link_to "Details", orders_show_path(order.id), class: "btn btn-primary" %>
                                <br><br>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/orders/show.html.erb
<div class="container-fluid mt-2 col-11 bg-dark text-white rounded">
    <h1>Order: <%= @order.item.description %> </h1>
    <h2>Seller: <%= @order.item.user.email %></h2>
    <br>
    <% @order.item.images.each do |photo| %>
        <%= image_tag(photo, :width => 200) %>
    <% end %>
    <br>
    <br>
    <strong>Price: </strong><%= number_to_currency(@order.item.price) %>
    <br>
    <strong>Condition: </strong><%= @order.item.condition %>
    <br>
    <strong>Date of Purchase: </strong><%= @order.created_at %>
    <br>
    <%= link_to "Message Seller",inboxes_path(inbox: {recipient_email: @order.item.user.email}), method: :post , class: "btn btn-primary" %>
    <br>
    <%= link_to 'Back', :back, class: "btn btn-dark" %>
</div>