config/routes.rb
Rails.application.routes.draw do
  get 'payments/success'
  get 'payments/failure'

  get 'orders/index'
  get 'orders/show/:id', to: "orders#show", as: "orders_show"

  resources :inboxes, except: [:edit, :update]
  post 'inboxes/message_create/:id', to: 'inboxes#message_create', as: "inbox_message_create"

  resources :addresses, except: [:create, :new, :index]
  resources :items
  get 'item/search(/:query)', to: "items#search", as: "item_search"


  devise_for :users, controllers: {
    registrations: "user/registrations"
  }

  root 'pages#index'
  get 'pages/index'

  get 'sample/sign/in', to: 'pages#sample_sign_in'

  mount ActionCable.server => '/cable'
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  include ApplicationConcern
  before_action :set_address, only: %i[ show edit update destroy ]
  before_action :authorized_user?
  before_action :address_inhabitant?
  
  # GET /addresses/1 or /addresses/1.json
  def show
    redirect_to edit_address_path(@address)
  end

  # GET /addresses/1/edit
  def edit
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    begin
      saved = @address.update!(address_params)
      save_redirector saved, @address, "Address was successfully updated."
    rescue ActiveRecord::RecordInvalid => e
      redirect_to edit_address_path(@address), notice: e.message
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:country, :state, :postal_code, :street_address, :premise, :sub_premise)
    end    

    # If an object get's saved correctly, redirects to that objects show with a message.
    def save_redirector saved, object, message
      respond_to do |format|
        if saved
          format.html { redirect_to object, notice: message }
          format.json { render :show, status: :ok, location: object }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: object.errors, status: :unprocessable_entity }
        end
      end
    end

    # Redirects if user isn't an inhabitant of the current address. Assumes user is signed id!
    def address_inhabitant?
      unless(@address.id == current_user.address_id)
        redirect_to root_path, notice: "You are not authorized to access that address!"
      end
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: address) do |form| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :country, class: "form-label"  %>
    <%= form.text_field :country, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :state, class: "form-label"  %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :postal_code, class: "form-label"  %>
    <%= form.text_field :postal_code, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :street_address, class: "form-label"  %>
    <%= form.text_field :street_address, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :premise, class: "form-label"  %>
    <%= form.text_field :premise, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :sub_premise, class: "form-label"  %>
    <%= form.text_field :sub_premise, class: "form-control" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<div class="container-fluid justify-content-center">
<h1 class="text-center">Editing Address</h1>

<div class="container-fluid row row-cols-md-1 g-4 justify-content-center">
  <div class="container-fluid col-10 col-md-5 bg-white rounded m-1 text-center">
        
        <%= render 'form', address: @address %>

        <%= link_to 'Back', edit_user_registration_path(current_user.address_id), class: "btn btn-dark text-white mb-3" %>
    </div>
</div>

app/views/addresses/index.html.erb
<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>State</th>
      <th>Postal code</th>
      <th>Street address</th>
      <th>Premise</th>
      <th>Sub premise</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.country %></td>
        <td><%= address.state %></td>
        <td><%= address.postal_code %></td>
        <td><%= address.street_address %></td>
        <td><%= address.premise %></td>
        <td><%= address.sub_premise %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', addresses_path %>