config/routes.rb
Rails.application.routes.draw do
  get 'payments/success'
  get 'payments/failure'

  get 'orders/index'
  get 'orders/show/:id', to: "orders#show", as: "orders_show"

  resources :inboxes, except: [:edit, :update]
  post 'inboxes/message_create/:id', to: 'inboxes#message_create', as: "inbox_message_create"

  resources :addresses, except: [:create, :new, :index]
  resources :items
  get 'item/search(/:query)', to: "items#search", as: "item_search"


  devise_for :users, controllers: {
    registrations: "user/registrations"
  }

  root 'pages#index'
  get 'pages/index'

  get 'sample/sign/in', to: 'pages#sample_sign_in'

  mount ActionCable.server => '/cable'
end

app/models/item.rb
class Item < ApplicationRecord
    has_one :order
    belongs_to :user
    has_many_attached :images, service: :amazon, dependent: :destroy

    # Validation
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :condition, presence: true
    validates :description, presence: true
    validates :part_type, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  before_action :item_owner?, only: [:edit, :update, :destroy]

  # GET /items or /items.json
  def index
    @items = current_user.items.all.includes(images_attachments: :blob)
  end

  def search
    require 'constants'
    @items = Item.all.includes(images_attachments: :blob)

    
    @part_types = Constants::PART_TYPES
  end

  # GET /items/1 or /items/1.json
  def show

    @item = Item.find(params[:id])

    if(user_signed_in?)
      @session = Stripe::Checkout::Session.create(
        success_url: "#{payments_success_url}?item_id=#{@item.id}",
        cancel_url: "#{payments_failure_url}",
        customer_email: current_user.email,
        payment_method_types: ['card'],
        line_items: [{
          # For metered billing, do not pass quantity
          currency: 'AUD',
          quantity: 1,
          name:@item.description,
          amount: @item.price.to_i*100,
        }],
        payment_intent_data: {
          metadata: {
            dish_id: @item.id
          }
        }
      )
    end
  end

  # GET /items/new
  def new
    require 'constants'
    @item = Item.new
    @part_types = Constants::PART_TYPES
  end

  # GET /items/1/edit
  def edit
    require 'constants'
    @part_types = Constants::PART_TYPES
  end

  # POST /items or /items.json
  def create
    @part_types = Constants::PART_TYPES
    @item = Item.new(item_params.merge(user_id: current_user.id))
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    @part_types = Constants::PART_TYPES
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:id, :price, :condition, :description, :seller_id, :part_type, images: [])
    end

    # Only the item owner may delete or edit an item.
    def item_owner?
      unless user_signed_in?  && !current_user.items.find_by(id: params[:id]).nil?
        flash.alert = "You are not authorized to access that!"
        redirect_to root_path
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="container col-6 text-end bg-white p-2 rounded">
  <%= form_with(model: item) do |form| %>

    <% if item.errors.any? %>
      <div id="error_explanation">
        <strong><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</strong>

        <ul>
          <% item.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3">
      <%= form.label :price , class: "form-label" %>
      <%= form.text_field :price, class: "form-control text-dark" %>
    </div>

    <div class="field mb-3">
      <%= form.label :condition, class: "form-label" %>
      <%= form.text_field :condition, class: "form-control text-dark" %>
    </div>

    <div class="field mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control text-dark" %>
    </div>

    <div class="field mb-3">
      <%= form.label :part_type, class: "form-label" %>
      <%= form.select :part_type, @part_types, class: "form-control text-dark" %>
    </div>

    <div class="field mb-3">
      <%= form.file_field :images, accept: 'image/png,image/jpeg', multiple: true , class: "btn btn-dark" %>
    </div>
  
    <div class="actions">
      <%= form.submit class: "btn btn-success mw-100" %>
      <div class="float-right">
        <%= link_to 'Back', items_path , class: "btn btn-danger" %>
      </div>
    </div>

  <% end %>
  
</div>

app/views/items/edit.html.erb
<h1 class="text-center">Editing Item</h1>

<%= render 'form', item: @item %>

app/views/items/index.html.erb
<div class="container-fluid justify-content-center">

  <div class="row">
    <div class="container-fluid col-12 col-md-6 text-right">
      <h1 style="min-width:200px;">My Items</h1>
    </div>
    <div class="container-fluid col-12 col-md-5 p-2">
      <%= button_to 'Sell New Item', new_item_path, class:"btn btn-primary float-right", method: :get %>
    </div>
  </div>

  <div class="row row-cols-1 row-cols-md-2 g-3 justify-content-center">
      <% @items.each do |item| %>
        <div class="card mb-3 m-2" style="max-width: 540px; min-width:200px ">
          <div class="row">
              <% unless item.images[0].nil? %>
                <div class="col-md-6">
                  <% item.images.each do |photo| %>
                    <%= image_tag(photo, :width => 200) %>
                  <% end %>
                </div>  
                <div class="col-md-6"> 
              <% else %>

                <div class="col-md-12"> 

              <% end%>
                  <div class="card-body">
                      <h5 class="card-title"><%= item.description %></h5>
                      <p class="card-text"><%= number_to_currency item.price %></p>
                      <p class="card-text"><%= item.condition %></p>
                      <p class="card-text"><%= item.status ? "Available" : "Sold" %></p>
                      <p class="card-text"><small class="text-muted">Posted <%= time_ago_in_words(item.created_at) %> ago.</small></p>
                      <%= link_to 'View', item , class: "btn btn-primary"%>
                      <%= link_to 'Edit', edit_item_path(item), class:"btn btn-warning" %>
                      <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
                  </div>
              </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="container justify-content-center">
    <div class="mb-3 text-center">
        <h1>New Item</h1>
    </div>

    <%= render 'form', item: @item %>
</div>

app/views/items/search.html.erb
<div class="container-fluid">
    <% query = "" %>
    <% if params.has_key?(:query) %>
        <% query = params[:query] %>
    <% end %>

    <div class="container-fluid col-8 p-2" style="max-width:600px">
        <div class="input-group input-group-lg bg-white rounded border">
            <input type="text" name="search" id="search" class="form-control border-0 text"  value=<%= query %>>
            <button id="searchButton" onclick='window.searchHandler()' class="btn btn-outline-secondary bg-dark text-white">Search!</button>
            <script>
                document.getElementById("search").addEventListener("keyup", function(e) {
                    if (e.keyCode === 13) {
                        document.getElementById("searchButton").click();
                    }
                })
            </script>
        </div>
    </div>

    <div class="row row-cols-1 row-cols-md-1 g-4 justify-content-center">
        <% if @items.count > 0 %>
            <% @items.each do |item| %>
                <% if (item.description.downcase.include?(query.downcase) ) %>
                    
                    <div class="card mb-3 m-2" style="max-width: 540px;">
                        <div class="row g-0">
                            <% unless item.images[0].nil?  %>
                                <div class="col-md-6">
                                    <% item.images.each do |photo| %>
                                        <%= image_tag(photo, :width => 200) %>
                                    <% end %>
                                    </div>  
                                    <div class="col-md-6"> 
                                <% else %>

                                    <div class="col-md-12"> 

                                <% end%>
                                <div class="card-body">
                                    <h5 class="card-title"><%= item.description %></h5>
                                    <p class="card-text"><%= number_to_currency item.price %></p>
                                    <p class="card-text"><%= item.condition %></p>
                                    <p class="card-text"><%= item.status ? "Available" : "Sold" %></p>
                                    <p class="card-text"><small class="text-muted">Posted <%= time_ago_in_words(item.created_at) %> ago.</small></p>
                                </div>
                            </div>
                            <a href="<%= item_path(item.id) %>" class="stretched-link"></a>
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
        <br>
    </div>
</div>

app/views/items/show.html.erb
<div class="container-fluid p-2 mt-2 col-11 bg-dark text-white rounded">
  <div>
    <% @item.images.each do |photo| %>
      <%= image_tag(photo, :width => 200) %>
    <% end %>
  </div>

  <p>
    <strong>Description:</strong>
    <%= @item.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @item.part_type %>
  </p>

  <p>
    <strong>Seller:</strong>
    <%= @item.user.email %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @item.price %>
  </p>

  <p>
    <strong>Condition:</strong>
    <%= @item.condition %>
  </p>

  <p>
    <strong>Availability: </strong>
    <%= @item.status ? "Available" : "Sold" %>
  </p>

  <% if user_signed_in?  && current_user.items.include?(@item) %>
    <br>
    <%= link_to 'Edit', edit_item_path(@item), class: "btn btn-warning" %>
  <% elsif user_signed_in?%>

    <% if @item.status %>
      <button type="button" data-stripe="payment" class="btn btn-success">Purchase</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        document.querySelector("[data-stripe='payment']").addEventListener("click", ()=>{
          console.log("Item.status == <%= @item.status %>: Cannot Proceed")
          if("<%= @item.status %>" == "true"){
            const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");

            stripe.redirectToCheckout({
              sessionId: "<%= @session.id %>"
            });
          }
        });
      </script>
    <% end %>

    <%= link_to "Message Seller",inboxes_path(inbox: {recipient_email: @item.user.email}), method: :post, class: "btn btn-primary" %>
  <% end %>

  <%= link_to 'Back', :back, class: "btn btn-light" %>