config/routes.rb
Rails.application.routes.draw do
  get 'payments/success'
  get 'payments/failure'

  get 'orders/index'
  get 'orders/show/:id', to: "orders#show", as: "orders_show"

  resources :inboxes, except: [:edit, :update]
  post 'inboxes/message_create/:id', to: 'inboxes#message_create', as: "inbox_message_create"

  resources :addresses, except: [:create, :new, :index]
  resources :items
  get 'item/search(/:query)', to: "items#search", as: "item_search"


  devise_for :users, controllers: {
    registrations: "user/registrations"
  }

  root 'pages#index'
  get 'pages/index'

  get 'sample/sign/in', to: 'pages#sample_sign_in'

  mount ActionCable.server => '/cable'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-0">
    <div class="container-fluid p-0">
        <a class="navbar-brand pl-3" href=<%= root_url %>><%= image_tag 'DS_logo.svg', size: "100x50" %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse p-2" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <%= link_to "Search Items", item_search_path, class: "nav-link" %>
                </li>
                <% if user_signed_in?%>
                    <li class="nav-item">
                        <%= link_to "My Items", items_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Inbox", inboxes_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Orders", orders_index_path , class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Edit Account", edit_user_registration_path(current_user.address_id), class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalSalvage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="container-fluid bg-secondary h-100 m-0 p-0 b-0" style="min-height:100vh; height=100%;">
  <body>
    
      <%= render "layouts/nav" %>
      <p class="notice p-0 m-0"><%= notice %></p>
      <%= yield %>
    
  </body>
  </div>
</html>